# GitHub Funding configuration
github: ezequiellich44-cmd
custom:
  - "https://solscan.io/account/3fZSMAyCEMhZwWiynbJDjoYNUT97aiV9BLzoUNroEMAz"
  - "https://etherscan.io/address/0x995fe0124034AD85571C3426cd49304EDcc985b5"